title: Dynamic Water
markdown: kramdown
kramdown:
  math-engine: katex
remote_theme: daattali/beautiful-jekyll
page-col: "#ffeb80"
footer-col: "#ffd678"
layout: minimal
plugins:
  - jekyll-title-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
